theme: jekyll-theme-cayman
google_analytics: UA-139093615-1
title: fcoin-manual
description: FCoinのトリセツ。
url: www.fcoin-manual.com

logo: ./images/fcoin-user-manual.png

twitter:
  username: lucied2007
  card: summary_large_image
defaults:
  - scope:
      path: ""
    values:
      image:
        path: ./images/fcoin-user-manual.png

docs:
  - tltle: 工事中
    url: sample.md