theme: jekyll-theme-cayman
google_analytics: UA-139093615-1
twitter:
  username: lucied2007
  card: /images/fcoin-user-manual.png
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/fcoin-user-manual.png