theme: jekyll-theme-cayman
google_analytics: UA-139093615-1
image: /images/fcoin-user-manual.png
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/fcoin-user-manual.png