theme: jekyll-theme-cayman
google_analytics: UA-139093615-1

logo: /images/fcoin-user-manual.png

twitter:
  username: lucied2007
  card: FCoinのトリセツ
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/fcoin-user-manual.png